import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                afacad: ['Afacad', 'sans-serif'],
                archivo: ['Archivo', 'sans-serif'],
                "label-md": ["Plus Jakarta Sans", "sans-serif"],
                "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
                "body-lg": ["Plus Jakarta Sans", "sans-serif"],
                "body-md": ["Plus Jakarta Sans", "sans-serif"],
                "title-lg": ["Plus Jakarta Sans", "sans-serif"],
                "label-sm": ["Plus Jakarta Sans", "sans-serif"],
                "headline-md": ["Plus Jakarta Sans", "sans-serif"],
                "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
                "display-lg": ["Plus Jakarta Sans", "sans-serif"],
            },
            colors: {
                "on-primary-fixed": "#410002",
                "on-background": "#141b2c",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "surface-container": "#e9edff",
                "outline-variant": "#e7bdb8",
                "tertiary-container": "#417f70",
                "on-tertiary-fixed": "#00201a",
                "tertiary": "#266658",
                "primary": "#ba0013",
                "on-tertiary-fixed-variant": "#065043",
                "on-primary": "#ffffff",
                "on-tertiary-container": "#f1fff9",
                "inverse-surface": "#293041",
                "surface-dim": "#d2daf0",
                "inverse-on-surface": "#edf0ff",
                "secondary-fixed-dim": "#b8cac9",
                "primary-fixed-dim": "#ffb4ab",
                "on-surface-variant": "#5d3f3c",
                "inverse-primary": "#ffb4ab",
                "surface-variant": "#dbe2f9",
                "on-surface": "#141b2c",
                "error": "#ba1a1a",
                "tertiary-fixed": "#afefdd",
                "surface-container-low": "#f1f3ff",
                "surface-bright": "#f9f9ff",
                "secondary": "#516161",
                "primary-fixed": "#ffdad6",
                "on-secondary-fixed-variant": "#3a4a49",
                "on-primary-container": "#fffafa",
                "surface-container-high": "#e0e8ff",
                "tertiary-fixed-dim": "#94d3c1",
                "on-secondary": "#ffffff",
                "outline": "#926f6b",
                "surface-container-highest": "#dbe2f9",
                "on-secondary-container": "#576867",
                "on-error": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface": "#f9f9ff",
                "background": "#f9f9ff",
                "on-primary-fixed-variant": "#93000d",
                "surface-tint": "#c00014",
                "surface-container-lowest": "#ffffff",
                "secondary-container": "#d4e6e5",
                "on-secondary-fixed": "#0e1e1e",
                "primary-container": "#e31e24",
                "secondary-fixed": "#d4e6e5",
            },
            borderRadius: {
                DEFAULT: "1.5rem",
                lg: "2.5rem",
                xl: "4rem",
                full: "9999px",
            },
            spacing: {
                base: "8px",
                xs: "4px",
                sm: "12px",
                md: "24px",
                lg: "40px",
                xl: "64px",
                gutter: "24px",
                "margin-mobile": "16px",
                "margin-desktop": "80px",
            },
            fontSize: {
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
                "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
                "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
            },
        },
    },
    plugins: [forms],
};
