import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        './resources/views/layouts/admin.blade.php',
        './resources/views/admin/**/*.blade.php',
    ],
    theme: {
        extend: {
            fontFamily: {
                'adm-body': ['Inter', 'sans-serif'],
                'adm-headline': ['Plus Jakarta Sans', 'sans-serif'],
            },
            colors: {
                'adm-bg': '#f8f9ff',
                'adm-surface': '#f8f9ff',
                'adm-surface-lowest': '#ffffff',
                'adm-surface-low': '#eff4ff',
                'adm-surface-container': '#e5eeff',
                'adm-surface-high': '#dce9ff',
                'adm-surface-highest': '#d3e4fe',
                'adm-surface-dim': '#cbdbf5',
                'adm-surface-bright': '#f8f9ff',
                'adm-primary': '#000000',
                'adm-on-primary': '#ffffff',
                'adm-primary-container': '#0d1056',
                'adm-on-primary-container': '#797ec5',
                'adm-on-primary-fixed': '#0d1056',
                'adm-on-primary-fixed-variant': '#3b4083',
                'adm-secondary': '#4059aa',
                'adm-on-secondary': '#ffffff',
                'adm-secondary-container': '#8fa7fe',
                'adm-on-secondary-container': '#1d3989',
                'adm-on-secondary-fixed': '#00164e',
                'adm-on-secondary-fixed-variant': '#264191',
                'adm-secondary-fixed': '#dce1ff',
                'adm-secondary-fixed-dim': '#b6c4ff',
                'adm-on-surface': '#0b1c30',
                'adm-on-surface-variant': '#464650',
                'adm-outline': '#777681',
                'adm-outline-variant': '#c7c5d2',
                'adm-error': '#ba1a1a',
                'adm-on-error': '#ffffff',
                'adm-error-container': '#ffdad6',
                'adm-on-error-container': '#93000a',
                'adm-inverse-surface': '#213145',
                'adm-inverse-on-surface': '#eaf1ff',
                'adm-inverse-primary': '#bfc2ff',
                'adm-surface-tint': '#53589c',
                'adm-dark': '#00004D',
                'adm-blue': '#1E3A8A',
                'adm-accent': '#3B82F6',
                'adm-success': '#10B981',
                'adm-warning': '#F59E0B',
                'adm-danger': '#EF4444',
                'adm-card': '#FFFFFF',
                'adm-border': '#E2E8F0',
                'adm-text-primary': '#0F172A',
                'adm-text-secondary': '#64748B',
            },
            fontSize: {
                'adm-headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'adm-headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'adm-headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'adm-body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'adm-body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'adm-body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'adm-label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
                'adm-label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'adm-display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
            },
        },
    },
    plugins: [],
};
